name = "emoji-maker-ai"
main = "worker/index.js"
compatibility_date = "2024-01-01"
account_id = "e7ec1bc89706c2e34029c1d07c3af8c37"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "QUOTA_KV"
id = "64739a85ab3f4554a4e978ea3b23b8a7"

[[workers]]
routes = [
  { pattern = "aiemojimaker.xyz", zone_name = "aiemojimaker.xyz" }
]
